version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    groups:
      androidx-and-kotlin:
        patterns: ["*"]
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
